# SPDX-FileCopyrightText: © 2026 Nathan Pugh <natepugh@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "td0-derive"
version = "0.1.0"
edition = "2024"

authors = ["Nathan Pugh <natepugh@gmail.com>"]
description = """
Derive macros for internal use in td0, a library for viewing and editing .TD0 e-kit/sample pad backup files.

Use the `td0` crate rather than using this crate directly.
"""
license = "GPL-3.0-or-later"
repository = "https://github.com/natepugh/libtd0"
keywords = ["td0", "Roland", "sampler", "sample pad", "drum kit"]
categories = ["parsing", "parser-implementations"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.3", features = ["extra-traits", "full"] }
td0-core = { path = "../td0-core" }
num-traits = "0.2.19"

[build-dependencies]
proc-macro2 = "1.0.107"
