# SPDX-FileCopyrightText: © 2026 Nathan Pugh <natepugh@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "td0-core"
version = "0.1.0"
edition = "2024"

authors = ["Nathan Pugh <natepugh@gmail.com>"]
description = """
Base types and functionality for td0, a library for viewing and editing .TD0 e-kit/sample pad backup files.

Use the `td0` crate rather than using this crate directly.
"""
license = "GPL-3.0-or-later"
repository = "https://github.com/natepugh/libtd0"
keywords = ["td0", "sampler", "sample pad", "drum kit"]
categories = ["parsing", "parser-implementations"]

[dependencies]
document-features = { version = "0.2.12" }
num-traits = "0.2.19"
zerocopy = { version = "0.8.55", features = ["derive"] }
zerocopy-derive = "0.8.56"

#! ### Optional dependencies
## Enable this feature to enable serde serialization of [`TD0Manifest`] objects.
serde = { version = "1.0.229", features = ["derive"], optional = true }

[dev-dependencies]
td0 = { path = "../td0" }

[features]
default = []
serde = ["dep:serde", "serde/derive"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
