[package]
name = "libtd0"
version = "0.1.0"
edition = "2024"

[lib]
name = "libtd0"
path = "src/lib.rs"

[[bin]]
name = "td0file"
path = "src/bin/main.rs"
required-features = ["cli"]

[features]
default = []
cli = [
    "dep:clap",
    "dep:csv",
    "dep:hexout",
    "dep:indexmap",
    "dep:serde",
    "dep:serde_json",
    "dep:serde_with",
    "indexmap/serde",
    "libtd0-core/serde",
]

[dependencies]
clap = { version = "4.6.1", features = ["derive"], optional = true }
hexout = { version = "0.3.2", optional = true }
md-5 = "0.11.0"
zerocopy = "0.8.52"
zerocopy-derive = "0.8.52"
libtd0-derive = { path = "libtd0-derive" }
libtd0-core = { path = "libtd0-core" }
serde = { version = "1.0.229", features = ["derive"], optional = true }
serde_json = { version = "1.0.151", optional = true }
csv = { version = "1.4.0", optional = true }
serde_with = { version = "3.22.0", optional = true }
indexmap = { version = "2.14.0", optional = true }

## TODO: Uncomment these clippy configs once major features are added.
[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

# Avoid panics
string_slice = "warn"
indexing_slicing = "warn"
panic = "warn"
todo = "warn"
unimplemented = "warn"
unreachable = "warn"
unchecked_time_subtraction = "warn"
panic_in_result_fn = "warn"

# Don't swallow errors
let_underscore_future = "warn"
let_underscore_must_use = "warn"
unused_result_ok = "warn"
assertions_on_result_states = "warn"

# Number safety
float_cmp = "warn"
float_cmp_const = "warn"
lossy_float_literal = "warn"
cast_sign_loss = "warn"
invalid_upcast_comparisons = "warn"
cast_possible_wrap = "warn"
cast_precision_loss = "warn"
cast_possible_truncation = "warn"

debug_assert_with_mut_call = "warn"
iter_not_returning_iterator = "warn"
expl_impl_clone_on_copy = "warn"
infallible_try_from = "warn"
dbg_macro = "warn"
