[package]
name = "libtd0"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
hexout = "0.3.2"
md-5 = "0.11.0"
thiserror = "2.0.18"
zerocopy = "0.8.52"
zerocopy-derive = "0.8.52"
libtd0-derive = { path = "libtd0-derive" }
libtd0-core = { path = "libtd0-core" }
fastnum = "0.7.5"
