[package]
name = "libtd0"
version = "0.1.0"
edition = "2024"

[lib]
name = "libtd0"
path = "src/lib.rs"

[[bin]]
name = "td0file"
path = "src/bin/main.rs"
required-features = ["cli"]

[features]
default = []
cli = [
    "dep:clap",
    "dep:csv",
    "dep:hexout",
    "dep:indexmap",
    "dep:serde",
    "dep:serde_json",
    "dep:serde_with",
    "indexmap/serde",
    "libtd0-core/serde",
]

[dependencies]
clap = { version = "4.6.1", features = ["derive"], optional = true }
hexout = { version = "0.3.2", optional = true }
md-5 = "0.11.0"
zerocopy = "0.8.52"
zerocopy-derive = "0.8.52"
libtd0-derive = { path = "libtd0-derive" }
libtd0-core = { path = "libtd0-core" }
serde = { version = "1.0.229", features = ["derive"], optional = true }
serde_json = { version = "1.0.151", optional = true }
csv = { version = "1.4.0", optional = true }
serde_with = { version = "3.22.0", optional = true }
indexmap = { version = "2.14.0", optional = true }

## TODO: Uncomment these clippy configs once major features are added.
#[lints.clippy]
#all = { level = "warn", priority = -1 }
#pedantic = { level = "warn", priority = -1 }
#nursery = { level = "warn", priority = -1 }
#restriction = { level = "warn", priority = -1 }

# Disable conflicting or overly pedantic restriction lints here:
#blanket_clippy_restriction_lints = "allow"
#implicit_return = "allow"
#pub_with_shorthand = "allow"