# SPDX-FileCopyrightText: © 2026 Nathan Pugh <natepugh@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "td0-model-ssxp"
version = "0.1.0"
edition = "2024"

authors = ["Nathan Pugh <natepugh@gmail.com>"]
description = """
SPD-SX Pro model implementation for td0, a parsing and editing library for the .TD0 e-kit/sample pad backup file format.

Rather than using this crate directly, use the `td0` crate with
the `model-spdsx-pro` feature compiled in. (as is the default.)
"""
license = "GPL-3.0-or-later"
repository = "https://github.com/natepugh/libtd0"
keywords = ["td0", "Roland", "sample pad", "SPD-SX Pro"]
categories = ["parsing", "parser-implementations"]

[dependencies]
td0-core = { path = "../td0-core" }
td0-derive = { path = "../td0-derive" }
md-5 = "0.11.0"
zerocopy = "0.8.60"
zerocopy-derive = "0.8.60"

[dev-dependencies]
hexout = "0.3.2"
pretty_assertions = "1.4.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(faster_incomplete_compile)'] }
