# SPDX-FileCopyrightText: © 2026 Nathan Pugh <natepugh@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "td0-cli"
version = "0.1.0"
edition = "2024"

authors = ["Nathan Pugh <natepugh@gmail.com>"]
description = "CLI utility for viewing and editing .TD0 e-kit/sample pad backup files."
license = "GPL-3.0-or-later"
repository = "https://github.com/natepugh/libtd0"
keywords = ["td0", "sampler", "sample pad", "drum kit"]
categories = ["parsing", "parser-implementations"]


[[bin]]
name = "td0file"
path = "src/main.rs"

[dependencies]
# td0 dependencies
td0 = { path = "../td0", version = "0.1.0" }
td0-core = { path = "../td0-core", version = "0.1.0", features=["serde"] }

# External dependencies
clap = { version = "4.6.7", features = ["derive"] }
csv = { version = "1.4.0" }
hexout = { version = "0.3.2" }
indexmap = { version = "2.14.2", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151" }
