# SPDX-FileCopyrightText: © 2026 Nathan Pugh <natepugh@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "td0"
version = "0.1.0"
edition = "2024"

authors = ["Nathan Pugh <natepugh@gmail.com>"]
description = "A parsing and editing library for the .TD0 e-kit/sample pad backup file format."
license = "GPL-3.0-or-later"
repository = "https://github.com/natepugh/libtd0"
keywords = ["td0", "sampler", "sample pad", "drum kit"]
categories = ["parsing", "parser-implementations"]

[features]
default = [
    "model-spdsx-pro",
]

model-spdsx-pro = [
    "td0-model-ssxp",
]

[dependencies]
# Internal crates
td0-core = { path = "../td0-core", version = "0.1.0" }
td0-derive = { path = "../td0-derive", version = "0.1.0" }
td0-model-ssxp = { path = "../td0-model-ssxp", optional = true, version = "0.1.0" }

# External dependencies
serde = { version = "1.0.229", features = ["derive"], optional = true }
serde_json = { version = "1.0.151", optional = true }
zerocopy = "0.8.60"
zerocopy-derive = "0.8.60"

[lints]
workspace = true
