# SPDX-FileCopyrightText: © 2026 Nathan Pugh <natepugh@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "libtd0-derive"
version = "0.1.0"
edition = "2024"

authors = ["Nathan Pugh <natepugh@gmail.com>"]
description = "Derive macros for internal use in libtd0. Use the `libtd0` crate instead."
license = "GPL-3.0-or-later"
repository = "https://github.com/natepugh/libtd0"
keywords = ["libtd0", "td0"]
categories = ["parsing", "parser-implementations"]

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.3", features = ["extra-traits", "full"] }
libtd0-core = { path = "../libtd0-core" }
num-traits = "0.2.19"

[lib]
proc-macro = true

[build-dependencies]
proc-macro2 = "1.0.107"
