# SPDX-FileCopyrightText: © 2026 Nathan Pugh <natepugh@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "pytd0"
version = "0.1.0"
edition = "2024"

authors = ["Nathan Pugh <natepugh@gmail.com>"]
description = "Python3 bindings for libtd0."
license = "GPL-3.0-or-later"
repository = "https://github.com/natepugh/libtd0"
keywords = ["libtd0", "td0"]
categories = ["parsing", "parser-implementations"]

[lib]
name = "pytd0"
crate-type = ["cdylib"]

[dependencies]
libtd0-core = { path = "../libtd0-core" }
multi-model = { path = "../multi-model" }

pyo3 = { version = "0.29.2", features = ["abi3", "abi3t", "experimental-inspect", "rust_decimal"] }
rust_decimal = "1.43.0"
