# SPDX-FileCopyrightText: © 2026 Nathan Pugh <natepugh@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "libtd0-core"
version = "0.1.0"
edition = "2024"

authors = ["Nathan Pugh <natepugh@gmail.com>"]
description = "Base types and functionality for libtd0. Use the `libtd0` crate instead."
license = "GPL-3.0-or-later"
repository = "https://github.com/natepugh/libtd0"
keywords = ["libtd0", "td0"]
categories = ["parsing", "parser-implementations"]

[lib]
name = "td0_core"
path = "src/lib.rs"

[dependencies]
document-features = { version = "0.2.12" }
num-traits = "0.2.19"
zerocopy = { version = "0.8.55", features = ["derive"] }
zerocopy-derive = "0.8.56"

#! ### Optional dependencies
## Enable this feature to enable serde serialization of [`TD0Manifest`] objects.
serde = { version = "1.0.229", features = ["derive"], optional = true }

[dev-dependencies]
libtd0 = { path = "../libtd0" }

[features]
default = []
serde = ["dep:serde", "serde/derive"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
