# SPDX-FileCopyrightText: © 2026 Nathan Pugh <natepugh@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "model-ssxp"
version = "0.1.0"
edition = "2024"

[dependencies]
libtd0-core = { path = "../libtd0-core" }
libtd0-derive = { path = "../libtd0-derive" }
md-5 = "0.11.0"
zerocopy = "0.8.52"
zerocopy-derive = "0.8.52"

[dev-dependencies]
hexout = "0.3.2"
pretty_assertions = "1.4.1"
