# SPDX-FileCopyrightText: © 2026 Nathan Pugh <natepugh@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "libtd0-model-ssxp"
version = "0.1.0"
edition = "2024"

authors = ["Nathan Pugh <natepugh@gmail.com>"]
description = "SPD-SX Pro model implementation for libtd0. Use the `libtd0` crate instead."
license = "GPL-3.0-or-later"
repository = "https://github.com/natepugh/libtd0"
keywords = ["libtd0", "td0", "SPD-SX Pro"]
categories = ["parsing", "parser-implementations"]

[lib]
name = "td0_model_ssxp"
path = "src/lib.rs"

[dependencies]
libtd0-core = { path = "../libtd0-core" }
libtd0-derive = { path = "../libtd0-derive" }
md-5 = "0.11.0"
zerocopy = "0.8.52"
zerocopy-derive = "0.8.52"

[dev-dependencies]
hexout = "0.3.2"
pretty_assertions = "1.4.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(faster_incomplete_compile)'] }